### ISSUE TITLE
Error while trying to send tokens

### ISSUE THREAD

**Issue by boduloman** [anonutopia/anonwallet#5]
I had 10.1 ANO in **wallet1** that I wanted to transfer to **wallet2**, to cover the fees I should send 9.8 ANO. 

When clicking send wallet gave me this error:
`Error: WavesRequestError: Server request to 'https://nodes.wavesnodes.com/assets/broadcast/transfer' has failed: { "error": 1, "message": "failed to parse json message", "cause": null, "validationErrors": { "obj.amount": [ { "msg": [ "error.expected.long" ], "args": [] } ] } }`

I tried multiple times with similar amounts 9.8, 9.7 always the same error. Then I tried to send just 5ANO and transaction passed through just fine. After that sent rest of 4.5 ANO to completely empty **wallet1** and that transaction also passed without any errors.
After that, I had 9.5 ANO on **wallet2**. Just to test the system again I have tried to send 9.2 ANO back to **wallet1** again the same error as before...

Later I wanted to reproduce that error with a bigger amount of tokens but without any success.

**Comment by anonpragmatic** [comment]
This one is fixed.
